// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	database "file-service/m/internal/database"

	mock "github.com/stretchr/testify/mock"
)

// Db is an autogenerated mock type for the Db type
type Db struct {
	mock.Mock
}

// SaveFile provides a mock function with given fields: file
func (_m *Db) SaveFile(file database.FileToSave) (int64, error) {
	ret := _m.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(database.FileToSave) (int64, error)); ok {
		return rf(file)
	}
	if rf, ok := ret.Get(0).(func(database.FileToSave) int64); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(database.FileToSave) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDb creates a new instance of Db. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *Db {
	mock := &Db{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
