environment: local
http_server: 
  address: localhost:8082
  timeout: 5s
  idle_timeout: 60s
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: file-service
storage_path: ./data/files
auth:
  user: admin
  password: admin